version: '2'
services:
  mongo:
    image: "mongo"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: "on-failure"

  socket:
    build: .
    ports:
      - "8181:8181"
    depends_on:
      - mongo
    restart: "on-failure"