version: '2'
services:
  mongo:
    image: "mongo"
    volume:
      - ./socket/data:/data/db
    ports:
      - "27017:27017"
  socket:
    build: .
    ports:
      - "8181:8181"
    depends_on:
      - mongo